package com.changyue.miaosha.dao;

import com.changyue.miaosha.bean.OrderDo;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 22 20:08:25 CST 2019
     */
    int insert(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 22 20:08:25 CST 2019
     */
    int insertSelective(OrderDo record);

}